language: node_js
node_js:
  - '8'

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:  ./node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
